import Head from 'next/head'
import Hero from '@/components/hero'
import Shot from '@/components/shot';
import Galeria from '@/components/galeria';
import Spacs from '@/components/spacs';
import Colors from '@/components/colors';
import Cta from '@/components/cta';
import Footer from '@/components/footer';



export default function Home() {
  return (
    <>
      <Head>
        <title>Drone Shop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Hero/>
        <Shot/>
        <Galeria/>
        <Spacs/>
        <Colors/>        
        <Cta/>
        <Footer/>
      </main>
    </>
  )
}
